/*****************************************************************************
 *
 * Copyright [2015] Qualcomm Technologies International, Ltd.
 *
 *
 ****************************************************************************/
/* Note: this is an auto-generated file. */

#ifndef __CSR_MESH_MCP_TYPES_H__
#define __CSR_MESH_MCP_TYPES_H__

#include "csr_types.h"

typedef enum _CSR_MESH_BOOLEAN
{
    CSR_MESH_BOOLEAN_FALSE = 0,
    CSR_MESH_BOOLEAN_TRUE = 1
}CSR_MESH_BOOLEAN_T;

typedef enum _CSR_MESH_POWER_STATE
{
    CSR_MESH_POWER_STATE_OFF = 0,
    CSR_MESH_POWER_STATE_ON = 1,
    CSR_MESH_POWER_STATE_STANDBY = 2,
    CSR_MESH_POWER_STATE_ONFROMSTANDBY = 3
}CSR_MESH_POWER_STATE_T;

typedef enum _CSR_MESH_DEVICE_INFORMATION
{
    CSR_MESH_DEVICE_INFORMATION_UUID_LOW = 0,
    CSR_MESH_DEVICE_INFORMATION_UUID_HIGH = 1,
    CSR_MESH_DEVICE_INFORMATION_MODEL_LOW = 2,
    CSR_MESH_DEVICE_INFORMATION_MODEL_HIGH = 3,
    CSR_MESH_DEVICE_INFORMATION_VID_PID_VERSION = 4,
    CSR_MESH_DEVICE_INFORMATION_APPEARANCE = 5,
    CSR_MESH_DEVICE_INFORMATION_LASTETAG = 6
}CSR_MESH_DEVICE_INFORMATION_T;

typedef enum _CSR_MESH_KEY_PROPERTIES
{
    CSR_MESH_KEY_PROPERTIES_ADMINISTRATOR = 0,
    CSR_MESH_KEY_PROPERTIES_USER = 1,
    CSR_MESH_KEY_PROPERTIES_GUEST = 2,
    CSR_MESH_KEY_PROPERTIES_RELAYONLY = 3
}CSR_MESH_KEY_PROPERTIES_T;

typedef enum _CSR_MESH_MONTH_OF_YEAR
{
    CSR_MESH_MONTH_OF_YEAR_UNKNOWN = 0,
    CSR_MESH_MONTH_OF_YEAR_JANUARY = 1,
    CSR_MESH_MONTH_OF_YEAR_FEBRUARY = 2,
    CSR_MESH_MONTH_OF_YEAR_MARCH = 3,
    CSR_MESH_MONTH_OF_YEAR_APRIL = 4,
    CSR_MESH_MONTH_OF_YEAR_MAY = 5,
    CSR_MESH_MONTH_OF_YEAR_JUNE = 6,
    CSR_MESH_MONTH_OF_YEAR_JULY = 7,
    CSR_MESH_MONTH_OF_YEAR_AUGUST = 8,
    CSR_MESH_MONTH_OF_YEAR_SEPTEMBER = 9,
    CSR_MESH_MONTH_OF_YEAR_OCTOBER = 10,
    CSR_MESH_MONTH_OF_YEAR_NOVEMBER = 11,
    CSR_MESH_MONTH_OF_YEAR_DECEMBER = 12
}CSR_MESH_MONTH_OF_YEAR_T;

typedef enum _CSR_MESH_TIMER_MODE
{
    CSR_MESH_TIMER_MODE_PROGRAMMING = 0,
    CSR_MESH_TIMER_MODE_ACTIVE = 1,
    CSR_MESH_TIMER_MODE_PARTLY_RANDOM = 2,
    CSR_MESH_TIMER_MODE_COMPLETELY_RANDOM = 3
}CSR_MESH_TIMER_MODE_T;

typedef enum _CSR_MESH_REMOTE_CODE
{
    CSR_MESH_REMOTE_CODE_NUMBER_0 = 0,
    CSR_MESH_REMOTE_CODE_NUMBER_1 = 1,
    CSR_MESH_REMOTE_CODE_NUMBER_2 = 2,
    CSR_MESH_REMOTE_CODE_NUMBER_3 = 3,
    CSR_MESH_REMOTE_CODE_NUMBER_4 = 4,
    CSR_MESH_REMOTE_CODE_NUMBER_5 = 5,
    CSR_MESH_REMOTE_CODE_NUMBER_6 = 6,
    CSR_MESH_REMOTE_CODE_NUMBER_7 = 7,
    CSR_MESH_REMOTE_CODE_NUMBER_8 = 8,
    CSR_MESH_REMOTE_CODE_NUMBER_9 = 9,
    CSR_MESH_REMOTE_CODE_DIRECTION_N = 16,
    CSR_MESH_REMOTE_CODE_DIRECTION_E = 17,
    CSR_MESH_REMOTE_CODE_DIRECTION_S = 18,
    CSR_MESH_REMOTE_CODE_DIRECTION_W = 19,
    CSR_MESH_REMOTE_CODE_DIRECTION_NE = 20,
    CSR_MESH_REMOTE_CODE_DIRECTION_SE = 21,
    CSR_MESH_REMOTE_CODE_DIRECTION_SW = 22,
    CSR_MESH_REMOTE_CODE_DIRECTION_NW = 23,
    CSR_MESH_REMOTE_CODE_DIRECTION_NNE = 24,
    CSR_MESH_REMOTE_CODE_DIRECTION_ENE = 25,
    CSR_MESH_REMOTE_CODE_DIRECTION_ESE = 26,
    CSR_MESH_REMOTE_CODE_DIRECTION_SSE = 27,
    CSR_MESH_REMOTE_CODE_DIRECTION_SSW = 28,
    CSR_MESH_REMOTE_CODE_DIRECTION_WSW = 29,
    CSR_MESH_REMOTE_CODE_DIRECTION_WNW = 30,
    CSR_MESH_REMOTE_CODE_DIRECTION_NNW = 31,
    CSR_MESH_REMOTE_CODE_SELECT = 32,
    CSR_MESH_REMOTE_CODE_CHANNEL_UP = 33,
    CSR_MESH_REMOTE_CODE_CHANNEL_DOWN = 34,
    CSR_MESH_REMOTE_CODE_VOLUME_UP = 35,
    CSR_MESH_REMOTE_CODE_VOLUME_DOWN = 36,
    CSR_MESH_REMOTE_CODE_VOLUME_MUTE = 37,
    CSR_MESH_REMOTE_CODE_MENU = 38,
    CSR_MESH_REMOTE_CODE_BACK = 39,
    CSR_MESH_REMOTE_CODE_GUIDE = 40,
    CSR_MESH_REMOTE_CODE_PLAY = 41,
    CSR_MESH_REMOTE_CODE_PAUSE = 42,
    CSR_MESH_REMOTE_CODE_STOP = 43,
    CSR_MESH_REMOTE_CODE_FAST_FORWARD = 44,
    CSR_MESH_REMOTE_CODE_FAST_REWIND = 45,
    CSR_MESH_REMOTE_CODE_SKIP_FORWARD = 46,
    CSR_MESH_REMOTE_CODE_SKIP_BACKWARD = 47
}CSR_MESH_REMOTE_CODE_T;

typedef enum _CSR_MESH_SENSOR_TYPE
{
    CSR_MESH_SENSOR_TYPE_UNKNOWN = 0,
    CSR_MESH_SENSOR_TYPE_INTERNAL_AIR_TEMPERATURE = 1,
    CSR_MESH_SENSOR_TYPE_EXTERNAL_AIR_TEMPERATURE = 2,
    CSR_MESH_SENSOR_TYPE_DESIRED_AIR_TEMPERATURE = 3,
    CSR_MESH_SENSOR_TYPE_INTERNAL_HUMIDITY = 4,
    CSR_MESH_SENSOR_TYPE_EXTERNAL_HUMIDITY = 5,
    CSR_MESH_SENSOR_TYPE_EXTERNAL_DEWPOINT = 6,
    CSR_MESH_SENSOR_TYPE_INTERNAL_DOOR = 7,
    CSR_MESH_SENSOR_TYPE_EXTERNAL_DOOR = 8,
    CSR_MESH_SENSOR_TYPE_INTERNAL_WINDOW = 9,
    CSR_MESH_SENSOR_TYPE_EXTERNAL_WINDOW = 10,
    CSR_MESH_SENSOR_TYPE_SOLAR_ENERGY = 11,
    CSR_MESH_SENSOR_TYPE_NUMBER_OF_ACTIVATIONS = 12,
    CSR_MESH_SENSOR_TYPE_FRIDGE_TEMPERATURE = 13,
    CSR_MESH_SENSOR_TYPE_DESIRED_FRIDGE_TEMPERATURE = 14,
    CSR_MESH_SENSOR_TYPE_FREEZER_TEMPERATURE = 15,
    CSR_MESH_SENSOR_TYPE_DESIRED_FREEZER_TEMPERATURE = 16,
    CSR_MESH_SENSOR_TYPE_OVEN_TEMPERATURE = 17,
    CSR_MESH_SENSOR_TYPE_DESIRED_OVEN_TEMPERATURE = 18,
    CSR_MESH_SENSOR_TYPE_SEAT_OCCUPIED = 19,
    CSR_MESH_SENSOR_TYPE_WASHING_MACHINE_STATE = 20,
    CSR_MESH_SENSOR_TYPE_DISH_WASHER_STATE = 21,
    CSR_MESH_SENSOR_TYPE_CLOTHES_DRYER_STATE = 22,
    CSR_MESH_SENSOR_TYPE_TOASTER_STATE = 23,
    CSR_MESH_SENSOR_TYPE_CARBON_DIOXIDE = 24,
    CSR_MESH_SENSOR_TYPE_CARBON_MONOXIDE = 25,
    CSR_MESH_SENSOR_TYPE_SMOKE = 26,
    CSR_MESH_SENSOR_TYPE_WATER_LEVEL = 27,
    CSR_MESH_SENSOR_TYPE_HOT_WATER_TEMPERATURE = 28,
    CSR_MESH_SENSOR_TYPE_COLD_WATER_TEMPERATURE = 29,
    CSR_MESH_SENSOR_TYPE_DESIRED_WATER_TEMPERATURE = 30,
    CSR_MESH_SENSOR_TYPE_COOKER_HOB_BACK_LEFT_STATE = 31,
    CSR_MESH_SENSOR_TYPE_DESIRED_COOKER_HOB_BACK_LEFT_STATE = 32,
    CSR_MESH_SENSOR_TYPE_COOKER_HOB_FRONT_LEFT_STATE = 33,
    CSR_MESH_SENSOR_TYPE_DESIRED_COOKER_HOB_FRONT_LEFT_STATE = 34,
    CSR_MESH_SENSOR_TYPE_COOKER_HOB_BACK_MIDDLE_STATE = 35,
    CSR_MESH_SENSOR_TYPE_DESIRED_COOKER_HOB_BACK_MIDDLE_STATE = 36,
    CSR_MESH_SENSOR_TYPE_COOKER_HOB_FRONT_MIDDLE_STATE = 37,
    CSR_MESH_SENSOR_TYPE_DESIRED_COOKER_HOB_FRONT_MIDDLE_STATE = 38,
    CSR_MESH_SENSOR_TYPE_COOKER_HOB_BACK_RIGHT_STATE = 39,
    CSR_MESH_SENSOR_TYPE_DESIRED_COOKER_HOB_BACK_RIGHT_STATE = 40,
    CSR_MESH_SENSOR_TYPE_COOKER_HOB_FRONT_RIGHT_STATE = 41,
    CSR_MESH_SENSOR_TYPE_DESIRED_COOKER_HOB_FRONT_RIGHT_STATE = 42,
    CSR_MESH_SENSOR_TYPE_DESIRED_WAKEUP_ALARM_TIME = 43,
    CSR_MESH_SENSOR_TYPE_DESIRED_SECOND_WAKEUP_ALARM_TIME = 44,
    CSR_MESH_SENSOR_TYPE_PASSIVE_INFRARED_STATE = 45,
    CSR_MESH_SENSOR_TYPE_WATER_FLOWING = 46,
    CSR_MESH_SENSOR_TYPE_DESIRED_WATER_FLOW = 47,
    CSR_MESH_SENSOR_TYPE_AUDIO_LEVEL = 48,
    CSR_MESH_SENSOR_TYPE_DESIRED_AUDIO_LEVEL = 49,
    CSR_MESH_SENSOR_TYPE_FAN_SPEED = 50,
    CSR_MESH_SENSOR_TYPE_DESIRED_FAN_SPEED = 51,
    CSR_MESH_SENSOR_TYPE_WIND_SPEED = 52,
    CSR_MESH_SENSOR_TYPE_WIND_SPEED_GUST = 53,
    CSR_MESH_SENSOR_TYPE_WIND_DIRECTION = 54,
    CSR_MESH_SENSOR_TYPE_WIND_DIRECTION_GUST = 55,
    CSR_MESH_SENSOR_TYPE_RAIN_FALL_LAST_HOUR = 56,
    CSR_MESH_SENSOR_TYPE_RAIN_FALL_TODAY = 57,
    CSR_MESH_SENSOR_TYPE_BAROMETRIC_PRESSURE = 58,
    CSR_MESH_SENSOR_TYPE_SOIL_TEMPERATURE = 59,
    CSR_MESH_SENSOR_TYPE_SOIL_MOISURE = 60,
    CSR_MESH_SENSOR_TYPE_WINDOW_COVER_POSITION = 61,
    CSR_MESH_SENSOR_TYPE_DESIRED_WINDOW_COVER_POSITION = 62
}CSR_MESH_SENSOR_TYPE_T;



CsrBool csr_mesh_validate_boolean_t(CSR_MESH_BOOLEAN_T val);
CsrBool csr_mesh_validate_power_state_t(CSR_MESH_POWER_STATE_T val);
CsrBool csr_mesh_validate_device_information_t(CSR_MESH_DEVICE_INFORMATION_T val);
CsrBool csr_mesh_validate_key_properties_t(CSR_MESH_KEY_PROPERTIES_T val);
CsrBool csr_mesh_validate_month_of_year_t(CSR_MESH_MONTH_OF_YEAR_T val);
CsrBool csr_mesh_validate_timer_mode_t(CSR_MESH_TIMER_MODE_T val);
CsrBool csr_mesh_validate_remote_code_t(CSR_MESH_REMOTE_CODE_T val);
CsrBool csr_mesh_validate_sensor_type_t(CSR_MESH_SENSOR_TYPE_T val);


CsrBool csr_mesh_validate_transaction_id(CsrUint8 var);
CsrBool csr_mesh_validate_gregorian_year(CsrUint16 var);
CsrBool csr_mesh_validate_day_of_month(CsrUint8 var);
CsrBool csr_mesh_validate_hour_of_day(CsrUint8 var);
CsrBool csr_mesh_validate_minute_of_hour(CsrUint8 var);
CsrBool csr_mesh_validate_minute_of_week(CsrUint16 var);
CsrBool csr_mesh_validate_second_of_minute(CsrUint8 var);
CsrBool csr_mesh_validate_fixed_degrees(CsrInt32 var);

int csr_mesh_size_of_boolean_t(void);
int csr_mesh_size_of_power_state_t(void);
int csr_mesh_size_of_device_information_t(void);
int csr_mesh_size_of_key_properties_t(void);
int csr_mesh_size_of_month_of_year_t(void);
int csr_mesh_size_of_timer_mode_t(void);
int csr_mesh_size_of_remote_code_t(void);
int csr_mesh_size_of_sensor_type_t(void);

#endif
